In [1]:
import numpy as np

# QUIZ - 10 SORU
#### (Cevapları tek satırda ifade ediniz)

## Sorular

1.Aşağıdaki numpy dizisinden çift sayıları çekiniz.

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Cevap :

2.Aşağıdaki numpy dizisinden merkezdeki dört elemanı "[[6, 7], [10, 11]]" çekiniz.

In [3]:
arr2 = np.array([[1,   2,   3,   4],
                 [5,   6,   7,   8],
                 [9,  10,  11,  12],
                 [13, 14,  15,  16]])

Cevap:

3.Aşağıdaki "A", "B" "C" matrisleri ile matris-matris çarpımı (ABC) yapınız.

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 5], [1, 4]])
C = np.array([[2, 4, 6], [1, 3, 5]])

Cevap:

4.Aşağıdaki numpy dizisinden [0, 0], [1, 1], [2, 3] koordinatlarındaki elemanları (1, 6 ve 12'i) çekiniz.

In [5]:
arr3 = np.array([[1,   2,   3,   4],
                 [5,   6,   7,   8],
                 [9,  10,  11,  12],
                 [13, 14,  15,  16]])

Cevap:

5.Aşağıdaki numpy dizisinden en büyük sayıyı çekiniz.

In [6]:
arr4 = np.array([[3, 7, 4, 1], [9, 2, 11, 5], [7, 6, 9, 1]])

Cevap:

6.10 elemanlı ve her elemanı 5-12 aralığında random bir tam sayı olan bir numpy dizisi üretiniz

Cevap:

7.Aşağıdaki 4x4 boyutlu numpy dizisini 8x2 boyutlu yapınız

In [7]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

Cevap:

8.Aşağıdaki numpy dizilerini sütun olarak stacklayıp bir matris elde ediniz.

In [8]:
col1 = np.array([1, 3, 5, 7])
col2 = np.array([2, 4, 6, 8])
col3 = np.array([1, 2, 3, 4])

Cevap:

9.8 elemanlı her elemanı 0-1 arasında random reel sayılardan oluşan numpy dizisi üretiniz.

Cevap:

10.Aşağıdaki int32 tipinden numpy dizisini float32'ye ediniz.

In [9]:
arr6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr6.dtype

dtype('int32')

Cevap:

## Cevaplar

In [10]:
arr1[arr1 % 2 == 0]

array([2, 4, 6, 8])

In [11]:
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [12]:
np.dot(A, np.dot(B, C))

array([[ 21,  55,  89],
       [ 51, 133, 215]])

In [13]:
arr3[[0, 1, 2], [0, 1, 3]]

array([ 1,  6, 12])

In [14]:
np.max(arr4)

11

In [15]:
np.random.randint(low=5, high=12, size=10)

array([ 7,  8, 10, 10,  7,  9, 10,  8,  5, 10])

In [16]:
arr5.reshape(8, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [17]:
np.column_stack([col1, col2, col3])

array([[1, 2, 1],
       [3, 4, 2],
       [5, 6, 3],
       [7, 8, 4]])

In [18]:
np.random.rand(8)

array([0.72226653, 0.01614481, 0.28579731, 0.16105995, 0.73031719,
       0.63057415, 0.71366612, 0.27721798])

In [19]:
arr6.astype("float32")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)